# Generated by Django 4.1.3 on 2022-11-29 16:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appliance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('location', models.CharField(default=None, max_length=50)),
                ('number', models.CharField(max_length=50)),
                ('description', models.CharField(blank=True, default=None, max_length=1024, null=True)),
                ('image_url', models.CharField(blank=True, default=None, max_length=512, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_from', models.DateTimeField(null=True)),
                ('day_to', models.DateTimeField(null=True)),
                ('appliance', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='booking.appliance')),
            ],
        ),
    ]
